services:
  db:
    image: postgres:15.2
    container_name: dvdrental-postgres
    restart: always
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
